

# This has been disabled due to costs on bitbucket. - RSE 2019
# This repo is mirrored at gitlab where the docker repo is now built
#  https://gitlab.com/robegan21/MetaBAT/pipelines


# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/default-image:latest

# enable Docker for your repository
#options:
#  docker: true
#
#pipelines:
#  default:
#    - step:
#        script: # Modify the commands below to build your repository.
#          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
#          - set -e
#          - export IMAGE_NAME=metabat/metabat
#          - docker version
#          # build the Docker image (this will use the Dockerfile in the root of the repo)
#          - docker build -t $IMAGE_NAME:$BITBUCKET_COMMIT .
#          - if [ "$BITBUCKET_BRANCH" == "master" ] ; then docker build -t $IMAGE_NAME:latest . ; fi
#          # authenticate with the Docker Hub registry
#          - docker login --username metabat --password $DOCKER_PASSWORD
#          # push the new Docker image to the Docker registry
#          - docker push $IMAGE_NAME

