# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - set -e
  - export METABAT_VERSION=$(git describe --tags)
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - cat /etc/issue 
  - apk add --no-cache openssh-client git
  - export METABAT_VERSION=$(git describe --tags)


build-master:
  stage: build
  script:
    - set -e
    - docker build -t "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" -t "$DOCKERHUB_USER/metabat:$CI_COMMIT_SHA" -t "$DOCKERHUB_USER/metabat:latest" -t "$DOCKERHUB_USER/metabat:$METABAT_VERSION" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD" $DOCKERHUB_REGISTRY
    - docker push $DOCKERHUB_USER/metabat
  only:
    - master

build:
  stage: build
  script:
    - set -e
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"  -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"  .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

  except:
    - master

after_script:
  - echo "Done"
